[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fzfy"
version = "0.0.2"
authors = [
  { name="Fernando Silveira", email="fsilveira@gmail.com" },
]
description = "A fzf wrapper"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/swrh/fzfy"
"Bug Tracker" = "https://github.com/swrh/fzfy/issues"
